config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'   # localhost:3000/welcome/index

  # resources: creates all the routes for the different actions we will add to our application
  resources :docs

  # for logged in users, can view their documents with authenticated_root
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  # localhost:3000 (for users who have not signed in yet!)
  root 'welcome#index'  

  





  # get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]

    def index
        # The @docs in index.html.erb are defined below in order of when they were created
        # @docs= Doc.all.order("created_at DESC")
        @docs = Doc.where(user_id: current_user)    # documents visible to only users who created them
    end

    def show            # find doc
    end

    def new
        @doc = current_user.docs.build      # only current user can create new document
    end

    def create      # create does not have a view
        # Doc.new is replaced with current_user.docs.build
        @doc = current_user.docs.build(doc_params)  # docs params are the document title and content

        if @doc.save
            redirect_to @doc        # if yes then redirect to that document that we just created
        else
            render 'new'            # else render the new file, gives a chance to recreate the document
        end
    end

    def edit            # find doc
    end

    def update      # update does not have a view
        if @doc.update(doc_params)
            redirect_to @doc        # find doc, then if the document is updated, it will save those chnages and redirect to that document
        else
            render 'edit'           # else render the edit page (Redirect is new HTTP request but rendering gives you chance to change and save again)
        end
    end

    def destroy
        @doc.destroy
        redirect_to docs_path       # find doc, then redirect to the index page
    end

    # private methods used with above actions
    private

        def find_doc
            @doc = Doc.find(params[:id])    # find the document by the id, then display the title and content of that document
        end

        def doc_params
            params.require(:doc).permit(:title, :content)   # referring to the doc model
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= simple_form_for @doc do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.button :submit, class: "button" %>
<% end %>
  

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
  <h1>Fix Doc!</h1>

  <%= render "form" %>

  <%= link_to "Cancel", doc_path %>
</div>

app/views/docs/index.html.erb
<div class="wrapper_with_padding">
  <div id="docs" class="clearfix">
    <% unless @docs.blank? %>
      <% @docs.each do |doc| %>
        <a href="<%= url_for(doc) %>">
          <div class="doc">
            <p class="title"><%= doc.title %></p>
            <p class="date"><%= time_ago_in_words(doc.created_at) %></p>
            <p class="content"><%= truncate(doc.content, length: 50) %></p>
          </div>
        </a>
      <% end %>
    <% else %>
      <h2>Create Doc!</h2>
      <p>Start Creating Documents and Organizing your life!</p>
      <button><%= link_to "Create Doc", new_doc_path %></button>
    <% end %>
  </div>
</div>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">
  <h1>New Doc!</h1>
  <%= render "form" %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
    <h1><%= @doc.title %></h1>
    <p><%= simple_format(@doc.content) %></p>

    <div class="buttons">
      <%= link_to "Fix Doc", edit_doc_path(@doc), class: "button" %>
      <%= link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet | Your life's work!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <div class="header_inner">
        <%= link_to "FileCabinet", root_path %>
        <nav>
          <% if user_signed_in? %>
            <%= link_to "Create Doc", new_doc_path %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </nav>
      </div>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>File Cabinet</h1>
    <p>Your life's work. Organized, always!</p>
    <button><%= link_to "Sign Up", new_user_registration_path %></button>
  </div>
</div>

<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <h2>Organize</h2>
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularized in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
      </div>
    </div>
  </div>
</div>

<div id="image_section">
  <div class="wrapper">
    <%= image_tag("typewriter.jpg", alt: "Image Description", class: "responsive-image") %>  
  </div>
</div>

<div id="bottom_cta">
  <div class="wrapper">
    <h2>Go Ahead!</h2>
    <br>
    <button><%= link_to "Join Now", new_user_registration_path %></button>
  </div>
</div>